name = "spine-consultants"
type = "webpack"

account_id = "14033e5125651d95fb1181e88d208a85"
workers_dev = 'true'
route = "https://www.spineconsultants.com.au"
zone_id = "0533394a63aab2bc66e341801e55e1d7"
compatibility_date = "2021-10-07"



